config/routes.rb
Rails.application.routes.draw do
  get 'homes/top'
  devise_for :users
  root to: 'homes#top'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :seminars do
   resources :post_comments, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :seminar
end

app/models/seminar.rb
class Seminar < ApplicationRecord
  belongs_to :user
  has_many :post_comments, dependent: :destroy
end

app/models/task.rb
class Task < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :seminars, dependent: :destroy
  has_many :post_comments, dependent: :destroy
         
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController
  def create
    seminar = Seminar.find(params[:seminar_id])
    comment = current_user.post_comments.new(post_comment_params)
    comment.seminar_id = seminar.id
    comment.save
    redirect_to seminar_path(seminar)
  end

  def destroy
    PostComment.find_by(id: params[:id], seminar_id: params[:seminar_id]).destroy
    redirect_to seminar_path(params[:seminar_id])
  end
  
    private

  def post_comment_params
    params.require(:post_comment).permit(:comment, :report)
  end
end

app/controllers/seminars_controller.rb
class SeminarsController < ApplicationController
  def index
    @seminars = Seminar.all
    @post_comments = PostComment.all
  end

  def new
    @seminar = Seminar.new
  end

  def create
    @seminar = Seminar.new(seminar_params)
    @seminar.user_id = current_user.id
    if @seminar.save
      redirect_to seminar_path(@seminar), notice: "投稿しました"
    else
      render(:new) && return
    end
  end

  def show
    @seminar = Seminar.find(params[:id])
    @post_comment = PostComment.new
  end


  def edit
    @seminar = Seminar.find(params[:id])
  end

  def update
    @seminar = Seminar.find(params[:id])
    @seminar.user_id = current_user.id
    if @seminar.update(seminar_params)
      redirect_to seminar_path(@seminar), notice: "更新しました"
    else
      render "edit"
    end
  end

  def destroy
    @seminar = Seminar.find(params[:id])
    @seminar.destroy
    redirect_to seminars_path
  end

  private
  def seminar_params
    params.require(:seminar).permit(:title, :starts_at, :ends_at)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.create(task_params)
    redirect_to tasks_path
  end
  
  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to tasks_path
  end
  
  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private
    def task_params
      params.require(:task).permit(:title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/seminars_helper.rb
module SeminarsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/homes/top.html.erb
    <main>
      <section id="magazine" class="wrapper">
        <div class="flex-item">
          <a class="item" href="#">
            <%= image_tag 'magazine-archive.jpg' %>
            <div class="text">
              <p class="title">Archive</p>
              <p>
                テキストテキストテキストテキスト<br>
                テキストテキストテキスト
              </p>
            </div>
          </a>
          <a class="item" href="#">
            <%= image_tag "magazine-new.jpg" %>
            <div class="text">
              <p class="title">New</p>
              <p>
                テキストテキストテキストテキスト<br>
                テキストテキストテキスト
              </p>
            </div>
          </a>
        </div>
      </section>

      <section id="fashion">
        <div class="wrapper">
          <h2 class="sec-title">Fashion & Style</h2>
          <p>
            テキストテキストテキストテキストテキストテキストテキストテキストテキストテキスト<br>
            テキストテキストテキストテキストテキストテキストテキストテキスト
          </p>
          <a class="btn" href="#">Read More</a>
        </div>
      </section>

      <section class="catalog-antique">
        <div class="flex-item wrapper">
          <div class="item">
            <%= image_tag "catalog.jpg" %>
          </div>
          <div class="item">
            <h2 class="sec-title">Catalog</h2>
            <p>
              テキストテキストテキストテキストテキストテキストテキストテキストテキスト
              テキストテキストテキストテキストテキストテキストテキストテキストテキスト
              テキストテキストテキストテキストテキストテキストテキストテキストテキスト
            </p>
            <p>
              テキストテキストテキストテキストテキストテキストテキストテキストテキスト
              テキストテキストテキストテキストテキストテキストテキストテキストテキスト
              テキストテキストテキストテキストテキストテキストテキストテキストテキスト
            </p>
            <p>
              テキストテキストテキストテキストテキストテキストテキストテキストテキスト
              テキストテキストテキストテキストテキストテキストテキストテキストテキスト
              テキストテキストテキストテキストテキストテキストテキストテキストテキスト
            </p>
          </div>
        </div>
      </section>

      <section class="catalog-antique">
        <div class="flex-item wrapper">
          <div class="item">
            <h2 class="sec-title">Antique</h2>
            <p>
              テキストテキストテキストテキストテキストテキストテキストテキストテキスト
              テキストテキストテキストテキストテキストテキストテキストテキストテキスト
              テキストテキストテキストテキストテキストテキストテキストテキストテキスト
            </p>
            <p>
              テキストテキストテキストテキストテキストテキストテキストテキストテキスト
              テキストテキストテキストテキストテキストテキストテキストテキストテキスト
              テキストテキストテキストテキストテキストテキストテキストテキストテキスト
            </p>
            <a class="btn" href="#">Read More</a>
          </div>
          <div class="item">
            <%= image_tag "antique.jpg" %>
          </div>
        </div>
      </section>
    </main>




<%= link_to 'enter', seminars_path %>

app/views/layouts/_header.html.erb
<header class="shadow-sm">
  <nav class="navbar navbar-expand-lg navbar-light">
    <div class="container">
      <%= link_to "ホーム", root_path %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'nav-link text-dark' %>
        </li>
        <li class="nav-item">
          <%= link_to "新規投稿", new_seminar_path, class: 'nav-link text-dark' %>
        </li>
        <li class="nav-item">
          <%= link_to "スケジュール", seminars_path, class: 'nav-link text-dark' %>
        </li>
        <% else %>
        <li class="nav-item">
          <%= link_to "新規登録", new_user_registration_path, class: 'nav-link text-dark' %>
        </li>
        <li class="nav-item">
          <%= link_to "ログイン", new_user_session_path, class: 'nav-link text-dark' %>
        </li>
        <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTodoSample</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>

app/views/seminars/_deadline.html.erb
 <p>期限 <%= @seminar.ends_at %>
      <br>
        <input type="hidden" id="userYear" value = "<%= @seminar.ends_at.year %>"  >
        <input type="hidden" id="userMonth"value = "<%= @seminar.ends_at.month %>" >
        <input type="hidden" id="userDate" value = "<%= @seminar.ends_at.day %>" >
        <input type="hidden" id="userHour" value = "<%= @seminar.ends_at.hour %>" >
        <input type="hidden" id="userMin"  value = "<%= @seminar.ends_at.min %>" >
        <input type="hidden" id="userSec"  value = "<%= @seminar.ends_at.sec %>" >
      </p>
      <p id="RealtimeCountdownArea" ></p>

<script>



function set2fig(num) {
   // 数値が1桁だったら2桁の文字列にして返す
   var ret;
   if( num < 10 ) { ret = "0" + num; }
   else { ret = num; }
   return ret;
}
function isNumOrZero(num) {
   // 数値でなかったら0にして返す
   if( isNaN(num) ) { return 0; }
   return num;
}
function showCountdown() {
   // 現在日時を数値(1970-01-01 00:00:00からのミリ秒)に変換
   var nowDate = new Date();
   var dnumNow = nowDate.getTime();

   // 指定日時を数値(1970-01-01 00:00:00からのミリ秒)に変換
   var inputYear  = document.getElementById("userYear").value;
   var inputMonth = document.getElementById("userMonth").value - 1;
   var inputDate  = document.getElementById("userDate").value;
   var inputHour  = document.getElementById("userHour").value;
   var inputMin   = document.getElementById("userMin").value;
   var inputSec   = document.getElementById("userSec").value;
   var targetDate = new Date( isNumOrZero(inputYear), isNumOrZero(inputMonth), isNumOrZero(inputDate), isNumOrZero(inputHour), isNumOrZero(inputMin), isNumOrZero(inputSec) );
   var dnumTarget = targetDate.getTime();

   // 表示を準備
   var dlYear  = targetDate.getFullYear();
   var dlMonth = targetDate.getMonth() + 1;
   var dlDate  = targetDate.getDate();
   var dlHour  = targetDate.getHours();
   var dlMin   = targetDate.getMinutes();
   var dlSec   = targetDate.getSeconds();
   var msg1 = "期限の" + dlYear + "/" + dlMonth + "/" + dlDate + " " + set2fig(dlHour) + ":" + set2fig(dlMin) + ":" + set2fig(dlSec);

   // 引き算して日数(ミリ秒)の差を計算
   var diff2Dates = dnumTarget - dnumNow;
   if( dnumTarget < dnumNow ) {
      // 期限が過ぎた場合は -1 を掛けて正の値に変換
      diff2Dates *= -1;
   }

   // 差のミリ秒を、日数・時間・分・秒に分割
   var dDays  = diff2Dates / ( 1000 * 60 * 60 * 24 );   // 日数
   diff2Dates = diff2Dates % ( 1000 * 60 * 60 * 24 );
   var dHour  = diff2Dates / ( 1000 * 60 * 60 );   // 時間
   diff2Dates = diff2Dates % ( 1000 * 60 * 60 );
   var dMin   = diff2Dates / ( 1000 * 60 );   // 分
   diff2Dates = diff2Dates % ( 1000 * 60 );
   var dSec   = diff2Dates / 1000;   // 秒
   var msg2 = Math.floor(dDays) + "日"
            + Math.floor(dHour) + "時間"
            + Math.floor(dMin) + "分"
            + Math.floor(dSec) + "秒";

   // 表示文字列の作成
   var msg;
   if( dnumTarget > dnumNow ) {
      // まだ期限が来ていない場合
      msg =  "十字架終了まで、あと" + msg2 ;
   }
   else {
      // 期限が過ぎた場合
      msg = msg1 + "は、既に" + msg2 + "前に過ぎました。";
   }

   // 作成した文字列を表示
   document.getElementById("RealtimeCountdownArea").innerHTML = msg;
   document.getElementById("deadline.id").value =  targetDate;

}
// 1秒ごとに実行
setInterval('showCountdown()',1000);

</script>

app/views/seminars/edit.html.erb
<%= form_with model: @seminar, local: true do |f| %>

    <div class="article-form-group">
        <div class="article-form-left">
            <p class"article-form-label">タイトル <span class="article-form-must">必須</span></p>
        </div>
        <div class="article-form-right">
            <p><%= f.text_field :title, class: "article_image" %></p>
        </div>
    </div>

    <div class="article-form-group">
        <div class="article-form-left">
            <p class"article-form-label">開始 <span class="article-form-must">必須</span></p>
        </div>
        
        <div class="article-form-right">
            <p><%= f.datetime_select :starts_at %></p>
        </div>
    </div>
    
    <div class="article-form-group">
        <div class="article-form-left">
            <p class"article-form-label">終わり <span class="article-form-must">必須</span></p>
        </div>
        
        <div class="article-form-right">
            <p><%= f.datetime_select :ends_at %></p>
        </div>
    </div>
    
    <tr class="actions">
      <%= f.submit "更新" ,class: 'btn btn-sm btn-success' %>
    </tr>
  <% end %>

app/views/seminars/index.html.erb
<div id="calendar"></div>

app/views/seminars/new.html.erb
<%= form_with model: @seminar, local: true do |f| %>

    <div class="article-form-group">
        <div class="article-form-left">
            <p class"article-form-label">タイトル <span class="article-form-must">必須</span></p>
        </div>
        <div class="article-form-right">
            <p><%= text_field :title, class: "article_image" %></p>
        </div>
    </div>

    <div class="article-form-group">
        <div class="article-form-left">
            <p class"article-form-label">開始 <span class="article-form-must">必須</span></p>
        </div>
        
        <div class="article-form-right">
            <p><%= f.datetime_select :starts_at %></p>
        </div>
    </div>
    
    <div class="article-form-group">
        <div class="article-form-left">
            <p class"article-form-label">終わり <span class="article-form-must">必須</span></p>
        </div>
        
        <div class="article-form-right">
            <p><%= f.datetime_select :ends_at %></p>
        </div>
    </div>
    
    <tr class="actions">
      <%= f.submit "新規登録" ,class: 'btn btn-sm btn-success' %>
    </tr>
  <% end %>

app/views/seminars/show.html.erb
<%= @seminar.title %>
<%= @seminar.starts_at.strftime('%Y/%m/%d') %>
<span>~</span></span>
<%= @seminar.ends_at.strftime('%Y/%m/%d') %>
<%= render 'seminars/deadline' %>
<%= link_to "編集", edit_seminar_path %>
<%= link_to '削除', seminar_path(@seminar), method: :delete, data: { confirm: '本当に消しますか？' } %>


<div class="comments">
<% @seminar.post_comments.each do |post_comment| %>
  <%= post_comment.user.name %>
  <%= post_comment.created_at.strftime('%Y/%m/%d') %>
  <%= post_comment.report %>
  <%= post_comment.comment %>
   <% if post_comment.user == current_user %>
  <div class="comment-delete">
    <%= link_to "削除", seminar_post_comment_path(post_comment.seminar, post_comment), method: :delete %>
  </div>
  <% end %>
<% end %>
</div>
<div class="new-comment">
<%= form_with(model:[@seminar, @post_comment], local: true) do |f| %>
  <%= f.select :report, [['できた', 'できた'], ['できなかった', 'できなかった']], { include_blank: "選択して下さい"} %>
  <%= f.text_area :comment, rows:'5',placeholder: "1日の振り返り" %>
  <%= f.submit "送信する" %>
<% end %>
</div>

app/views/tasks/edit.html.erb
<h1>タスク編集</h1>
<%= form_for(@task) do |f| %>
  <div><%= f.label :title %></div>
  <div><%= f.text_field :title %></div>
  <div><%= f.submit %></div>
<% end %>
<%= link_to '戻る', tasks_path %>

app/views/tasks/index.html.erb
<h1>タスク一覧</h1>
<table>
  <thead>
    <tr>
      <th>タスク名</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.title %></td>
        <td><%= link_to '編集', edit_task_path(task) %></td>
        <td><%= link_to '削除', task_path(task), method: :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to '追加', new_task_path %>

app/views/tasks/new.html.erb
<h1>新規タスク</h1>
<%= form_for(@task) do |f| %>
  <div><%= f.label :title %></div>
  <div><%= f.text_field :title %></div>
  <div><%= f.submit %></div>
<% end %>
<%= link_to '戻る', tasks_path %>